#ifndef FT_LSTMAP_H
#define FT_LSTMAP_H

/*
* Generate and return a new t_list where the content of each element is 
* generated by a function f from the content of the t_list given as an argument
*/
t_list *ft_lstmap(t_list *lst, void *(*f)(void *), void (*del)(void *));

#endif /* FT_LSTMAP_H */