#ifndef LIBFT_H
#define LIBFT_H

/* Some functions need these libraries */
#include <stdlib.h>
#include <unistd.h>

#include "ft_isalpha.h"
#include "ft_isdigit.h"
#include "ft_isalnum.h"
#include "ft_isascii.h"
#include "ft_isprint.h"
#include "ft_toupper.h"
#include "ft_tolower.h"
#include "ft_calloc.h"
#include "ft_strlen.h"
#include "ft_bzero.h"
#include "ft_strchr.h"
#include "ft_memset.h"
#include "ft_memcpy.h"
#include "ft_memmove.h"
#include "ft_strlcpy.h"
#include "ft_atoi.h"
#include "ft_strlcat.h"
#include "ft_strrchr.h"
#include "ft_strncmp.h"
#include "ft_memchr.h"
#include "ft_memcmp.h"
#include "ft_strnstr.h"
#include "ft_strdup.h"
#include "ft_substr.h"
#include "ft_strjoin.h"
#include "ft_strtrim.h"
#include "ft_split.h"
#include "ft_itoa.h"
#include "ft_strmapi.h"
#include "ft_striteri.h"
#include "ft_putchar_fd.h"
#include "ft_putstr_fd.h"
#include "ft_putendl_fd.h"
#include "ft_putnbr_fd.h"
#include "ft_t_list.h"
#include "ft_lstnew.h"
#include "ft_lstadd_front.h"
#include "ft_lstsize.h"
#include "ft_lstlast.h"
#include "ft_lstadd_back.h"
#include "ft_lstdelone.h"
#include "ft_lstclear.h"
#include "ft_lstiter.h"
#include "ft_lstmap.h"
#include "ft_lstpop_front.h"

#endif /* LIBFT_H */
